spring.application.name=inventory-control-app

# Configuration PostgreSQL Database
spring.datasource.url=jdbc:postgresql://${HOST_DB}:5432/${DB_NAME}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Configuration
# max-pool = Tamaño del pool de conexiones (ajustable segun tus necesidades)
# idle-timeout = Tiempo de espera en ms para conexiones inactivas
# timeout = Tiempo de espera en ms para obtener una connection
# minimum-idle = Numero minimo de conexiones inactivas en el pool

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
